apiVersion: v1
kind: Service
metadata:
  name: ajj-app-service
  namespace: ajj-jujitsu
  labels:
    app: ajj-app
spec:
  type: ClusterIP
  selector:
    app: ajj-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

# Made with Bob
